apiVersion: install.package.carvel.dev/v1alpha1
kind: InstalledPackage
metadata:
  name: hello-world-2-0-0
  namespace: demo-3-ns
spec:
  serviceAccountName: demo-3-sa
  packageRef:
    publicName: hello-world.carvel.dev
    version: 2.0.0
  values:
    - secretRef:
        name: hello-world-2.0.0-values
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-2.0.0-values
  namespace: demo-3-ns
stringData:
  0-values.yml: |
    app:
      message: Message from InstalledPackage for version 2.0.0
