#@ load("@ytt:data", "data")

#@ load("helpers.star",projectsCRD="projectsCRD")
---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: #@ projectsCRD()
spec:
  group: #@ data.values.crd.group
  version: #@ data.values.crd.version
  scope: "Namespaced"
  names:
    plural: "projects"
    singular: "project"
    kind: "Project"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["name"]
          properties:
            name:
              type: "string"
            description:
              type: "string"
