apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: hello-world-helm.1.1.0
spec:
  publicName: hello-world.carvel.dev
  version: 1.1.0
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: gcr.io/cf-k8s-lifecycle-tooling-klt/demo-hello-world-bundle@sha256:1394117160e6c5d64a073998169cc7821b54c85013160a34763d7ec9bed7c9dc
      template:
        - helmTemplate:
            path: .
        - kbld:
            paths:
              - "-" # Read the output of the helm template command and provide it to `kbld`
              - .imgpkg/images.yml # Used to update the image location if the bundle was copied between registries
      deploy:
        - kapp: { }
